# Generated by Django 6.0.5 on 2026-06-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='pratos/'),
        ),
    ]
